### ISSUE TITLE
Add “S-CysGly” modification (monoisotopic +176.026)

### ISSUE THREAD

**Issue by rfellers** [HUPO-PSI/psi-mod-CV#13]
In the midst of working with one of our collaborators, we ran into the need to annotate an “S-CysGly” modification (monoisotopic +176.026).  My search of RESID, PSI-MOD, and Unimod turned up nothing.  Paul Thomas then informed us that it is a breakdown product of S-glutathione (AA0229) and you can see evidence of its existence in manuscript form here: http://www.sciencedirect.com/science/article/pii/S1046202311002520 (Table 1).  Would you be willing to add this mod?

**Comment by pmt706** [comment]
Hi Ryan,  

Certainly.  Once the current pull request is approved, I'll get this in the queue.

Paul

**Comment by ricardblum** [comment]
Hi All,

It would be a good thing to add the S-CysGly  (S-cysteinylglycine) modification. There are other evidences of its existence in PMID 27936627, PMID 20594348 and PMID 29627744. 
It is indeed a degradation product of glutathione. Glutamyl-transpeptidase cleaves glutathione into cysteinylglycine (Cys-Gly) and a Glu residue (reviewed in PMID 28537416).

Sylvie.
