### ISSUE TITLE
Crossreference with GNO

### ISSUE THREAD

**Issue by pmt706** [HUPO-PSI/psi-mod-CV#15]
All,

I'd like to propose generating cross-references in PSI-MOD with the the glycan naming ontology, GNO (http://obofoundry.org/ontology/gno.html).  Working with Nathan Edwards of the GNO to determine which terms cross-reference.

Paul

**Comment by edeutsch** [comment]
sounds good. Can it be automated fairly readily?

**Comment by pmt706** [comment]
Definitely! Nathan's already got a draft mapping put together, I'm going to review and confirm!
