### ISSUE TITLE
Duplicated short label

### ISSUE THREAD

**Issue by sandraorchard** [HUPO-PSI/psi-mod-CV#23]
N-phosphorylated residue MOD:01456 and O-phosphorylated residue MOD:01455 have both been given the Short label curated by PSI-MOD
OPhosRes

Please could that of MOD:01456 be changed to NPhosRes with some urgency as the wrong term is being used by IMEx as a result.

**Comment by pmt706** [comment]
Hi Sandra,

Good catch!  I've made the change and will push it momentarily.  I'm trying to find and address bugs like this.

Paul

**Comment by sandraorchard** [comment]
Hardly a 'good catch' - its taken up nearly 20 years to notice and then it had to be pointed out by a user :)

Thank you for the prompt service.
Sandra
