### ISSUE TITLE
SARS-Cov-2 Spike glycosylations needed from UniMod

### ISSUE THREAD

**Issue by rwst** [HUPO-PSI/psi-mod-CV#25]
Hello,
in order to be able to curate SARS-Cov-2 the Reactome team is in need of the following PTMs in PSI-MOD. Can you please import them?

- dHex(1)Hex(4)HexNAc(5) --- UNIMOD:1519
- dHex(2)Hex(4)HexNAc(5) --- UNIMOD:1785
- dHex(1)Hex(5)HexNAc(5) --- UNIMOD:1555
- dHex(1)Hex(5)HexNAc(3) --- UNIMOD:1484
- dHex(1)Hex(3)HexNAc(6) --- UNIMOD:1781
- dHex(1)Hex(6)HexNAc(3) --- UNIMOD:1509
- Hex(9)HexNAc(2) --- UNIMOD:1531
- Hex(7)HexNAc(2) --- UNIMOD:1480

These are all children of complex glycosylation MOD:00725

**Comment by pmt706** [comment]
Hi, Sorry for missing this! Yes.  I can add these new terms.
