### ISSUE TITLE
NTR: urmylation

### ISSUE THREAD

**Issue by Shellerstedt** [HUPO-PSI/psi-mod-CV#26]
Hi, 

I can’t seem to find a term for urmylation (GO: “Covalent attachment of the ubiquitin-like protein URM1 to another protein”) and would like to request a new term if possible (or point me in the right direction if I’m missing something?)

Some relevant references:

Furukawa K, et al. (2000) A protein conjugation system in yeast with homology to biosynthetic enzyme reaction of prokaryotes. J Biol Chem 275(11):7462-5
PMID: 10713047

Van der Veen AG, et al. (2011) Role of the ubiquitin-like protein Urm1 as a noncanonical lysine-directed protein modifier. Proc Natl Acad Sci U S A 108(5):1763-70
PMID: 21209336

Looks like the appropriate term would be “urmylation” or perhaps “urmylated lysine.”

Thanks for your help!

Best, 
Sage (SGD curator)

**Comment by pmt706** [comment]
Hi Sage,

We can add that.  How does it connect to the protein? Through a lysine bond to a C-terminal glycine like Ubiq/SUMO/NEDD? The papers you provided seem to indicate that, but I'll admit that I didn't dig too deeply beyond the abstract

Can you help with the term definitions? Does this look correct?

Thanks!
Paul

[Term]
id: MOD:XXXXXX <-- I will fill this in
name: urmylated lysine
def: "A protein modification that effectively crosslinks the N6-amino of a peptidyl lysine with the carboxyl-terminal glycine of a URM1 protein." [PubMed:10713047, PubMed:21209336]
subset: PSI-MOD-slim
xref: Origin: "K"
xref: Source: "natural"
xref: TermSpec: "none"
is_a: MOD:00908 ! modified glycine residue
is_a: MOD:01875 ! N6-acylated L-lysine
relationship: contains MOD:00134 ! N6-glycyl-L-lysine

**Comment by pmt706** [comment]
Hearing nothing, I'm just going to create this term.  Let me know if there are any questions/concerns.

**Comment by edeutsch** [comment]
Looks good to me. Is there any appropriate mass delta?

**Comment by pmt706** [comment]
It's an intact protein mod like SUMO/Ubiquitin, so I'm voting against having it specified mass delta... just specifying it "higher" in the ontology.

**Comment by edeutsch** [comment]
okay, then fine for me, thanks!

**Comment by Shellerstedt** [comment]
Apologies for the delay - I was out part of last week and wanted to confirm it with a colleague. This looks good to us. Thank you for your help! 

Best, 
Sage
