### ISSUE TITLE
Update from pride team with more annotations 

### ISSUE THREAD

**Issue by ypriverol** [HUPO-PSI/psi-mod-CV#3]
Hi @mwalzer 
For pride resources I have updated this ontology with better cross references to unimod. If you like the idea we can work with that updated file instead of the old one.

Best regards
Yasset

**Comment by mwalzer** [comment]
I think improved interoperability is super useful

**Comment by mwalzer** [comment]
I definitively think we should include updates

**Comment by noedelta** [comment]
It will work for us too
