### ISSUE TITLE
AVERAGE Itraq4PLEX MOD

### ISSUE THREAD

**Issue by pabinz** [HUPO-PSI/psi-mod-CV#31]
Add a mod that represents the average of all 4 Itraq4PLEX reporter+balance mods; it is a representing average iTRAQ4plex reporter+balance for all iTRAQ at a resolution of below 0.1Da

Term]
id: MOD:nnnnnnnn
name: iTRAQ4plex reporter+balance reagent acylated residue, average mass modification
def: "A protein modification that effectively replaces a hydrogen atom of a residue with one of the Applied Biosystems iTRAQ4plex reagent reporter+balance groups." [Unimod:214]
comment: The reagent consists of a reporter group, a balance group and a protein reactive N-oxysuccinimide group. The reporter group, an isotopically labeled 1,4-dimethylpiperazine, is connected to a carbonyl balance group that is isotopically labeled to produce a nominally isobaric combined modification. Four versions of chemically identical iTRAQ4plex moyeties, but with different isotope distribution. This modification is calculated as the average of the four species. It has no isotopic distribution reality, the exact mass does not correspond to any real isotopic distribution.   
subset: PSI-MOD-slim
synonym: "(4-methylpiperazin-1-yl)acetyl" EXACT PSI-MOD-alternate []
synonym: "iTRAQ" RELATED Unimod-interim []
xref: DiffAvg: "144.10"
xref: DiffFormula: "none"
xref: DiffMono: "144.102411"
xref: Formula: "none"
xref: MassAvg: "none"
xref: MassMono: "none"
xref: Origin: "X"
xref: Source: "artifact"
xref: TermSpec: "none"
is_a: MOD:01426 ! isotope tagged reagent derivatized residue
is_a: MOD:01705 ! isotope tagged reagent acylated residue
is_a: MOD:01709 ! iTRAQ4plex reporter+balance reagent N-acylated residue
is_a: MOD:01513 ! modifications with monoisotopic mass differences that are nominally equal at a resolution below 0.1 Da

**Comment by edeutsch** [comment]
This looks good to me. @pmt706 can you create a PR if you're okay with this?

**Comment by pmt706** [comment]
Yep.  Will do.
