### ISSUE TITLE
Our OBOFoundry link points to an old version of the PSI-MOD.obo file.  

### ISSUE THREAD

**Issue by pmt706** [HUPO-PSI/psi-mod-CV#38]
I'm working with the OBOFoundry folks to get this updated and will close this ticket as soon as that's done.

**Comment by pmt706** [comment]
Need to generate an OWL file for our OBO to get get happy with the OBOFoundry folks (this is needed for UniProt to fix their crosslinks... long story.)

Using the [ROBOT tool](http://robot.obolibrary.org/), I'm running this command: 

java  -jar C:\Users\Paul\Desktop\ROBOT\robot.jar convert --input c:\Users\Paul\Documents\GitHub\psi-mod-CV\PSI-MOD.obo --output c:\Users\Paul\Documents\GitHub\psi-mod-CV\PSI-MOD.owl

**Comment by edeutsch** [comment]
If this works, we should consider doing the same to PSI-MS.

**Comment by pmt706** [comment]
This seems to be working, the repo manager over @ obofoundry is really helpful (and the last author on the ROBOT paper too).  Got our new OWL in a PR over there.

**Comment by pmt706** [comment]
The PURLs for PSI-MOD are all updated and have been picked up by both ONTOBEE and OLS overnight (and should in the future now too!)  Let me know if you decide to do the same with PSI-MS and if you run into any issues!
