### ISSUE TITLE
Mass Differences... Are they a transitive property?

### ISSUE THREAD

**Issue by pmt706** [HUPO-PSI/psi-mod-CV#47]
Hi All,

**A Specific Example:**
MOD:00394 is "acetylated residue" with a mass difference of ~42... however, MOD:00648 is for N,O-diacetylated L-serine, which points up MOD:00394 (through MOD:00647, acetylated L-serine) ... the mass difference of MOD:00648 is ~84 (2x42)... All of the other children of MOD:00394 have a Mass difference of 42... should we address this? 

More generally, is it understood/accepted that mass difference is transitive through the is_a relationship? If MOD_A is_a MOD_B MUST DiffMassA==DiffMassB? further... if MOD_B is_a MOD_C, MUST DiffMassA==DiffMassC?

@rfellers is working on a mapping project with the new ProForma standard and this question sort of came up while we were trying to hash identical proteoforms... 

Thoughts?

**Comment by edeutsch** [comment]
I am uncertain, but I would lean yes. Maybe the top parent term should be "acetylated residue" without a mass, and then abstract children "monoacetylated residue" and "diacetylated residue" would be the first to carry a mass and have MOD:00647 et al. as children as appropriate?

**Comment by ricardblum** [comment]
I agree with Eric's suggestion.

Sylvie.

Le 14/12/2020 à 22:41, Eric Deutsch a écrit :

**Comment by pmt706** [comment]
So, I'll add that disambiguation in the next PR candidate... but what about the general case... MUST parent term mass differences be identical to their children to ensure the transitive nature of the is_a relationship?  I think they MUST... based on [this paper from Barry Smith](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1175958/).
![image](https://user-images.githubusercontent.com/5824906/102237786-a3ed2900-3eba-11eb-998b-aed1b7aece20.png)

Given this, I think we need to look at all of the is_a relationships and determine if is_a is the right way to go... For instance... there are some PTMs that are both hydroxylated and methylated... those, by rule shouldn't be related by the "is_a" relationship to methylated residue and/or hydroxylated residue, because those are just partial relationships and should probably be reclassified to "part_of" instead.

**Comment by edeutsch** [comment]
I think the answer is probably yes, but I am uncertain. Perhaps examining some more examples is a good way to get comfortable with it. Using part_of seems reasonable in the way that you describe, although I'm not certain I understand. part_of seems useful for a subcomponent. But what about a superset? Are you contemplating a single PTM that is hydroxylated and methylated that is a parent to a hydroxylated PTM or a *child* of a hydroxylated PTM?

**Comment by pmt706** [comment]
I need to read that paper a bit more fully (and maybe email with a couple of folks I know in the ontology community) and see what the best relationship would be... Maybe the better one would be "has_part" instead of "part_of" or "derives_from"

**Comment by edeutsch** [comment]
It seems tidier to me to always list parents, rather than sometimes parents and sometimes children.

**Comment by pmt706** [comment]
agreed, I would want to keep the directionality one-way "up the tree" (and let people use conventional logic to reason down the tree) it's just a matter of selecting the correct relationships.  In the current PR for the di-acetyl, it's just one-way.  I simply deleted the unmatched is_a's.

**Comment by edeutsch** [comment]
ah, okay, I just brought it up because "has_part" goes the other way?

**Comment by pmt706** [comment]
@rfellers, being the awesome guy he is, wrote a script to look for these issues of transitivity and I'm addressing them in the next push. Fun fact, just over 100 issues existed across all of the 3000+ is_a relationships, so knocking them out shouldn't be too hard.

**Comment by edeutsch** [comment]
awesome! Many thanks to you both for really tidying PSI-MOD up!
