### ISSUE TITLE
PSI-MOD.obo.xml not up to date

### ISSUE THREAD

**Issue by mwalzer** [HUPO-PSI/psi-mod-CV#5]
PSI-MOD.obo.xml update after #4 missing

**Comment by edeutsch** [comment]
Does anyone know how this XML is generated? I presume it is generated via a script that reads the OBO file and generates the XML?

Does anyone know where the script can be found? Or who might know?

thanks,
Eric

**Comment by pmt706** [comment]
I'm going to propose that we delete the .obo.xml or in some way mark it as deprecated.  I don't have a way to generate the .obo.xml (which isn't OWL, but rather just a serialized obo file) and I don't plan on reverse-engineering it... thoughts?

**Comment by edeutsch** [comment]
I think I tried reaching out to John G back in Feb and did not get a response. I agree that we should not keep an obsolete file in master lest someone try to use it. I concur that we should delete it and then try to re-create it if someone complains.

**Comment by ricardblum** [comment]
I agree.

Best wishes.

Sylvie.

Professor Sylvie RICARD-BLUM
Pericellular and Extracellular Supramolecular Assemblies
UMR 5246 CNRS - University Lyon 1
Institute of Molecular and Supramolecular Chemistry and Biochemistry
University Claude Bernard Lyon 1, 43 Boulevard du 11 novembre 1918
69622 Villeurbanne Cedex, France
Phone: +33(0)4 72 44 82 32
E-mail: sylvie.ricard-blum@univ-lyon1.fr
http://www.icbms.fr
The French Society for Matrix Biology http://www.sfbmec.fr
The International Society for Matrix Biology http://ismb.org

Le 30/11/2020 à 22:41, Eric Deutsch a écrit :

**Comment by pabinz** [comment]
In principle I agree.
I have no views on users of the xml version, which is anyway not the official source format.


De : pmt706 <notifications@github.com>
Envoyé : lundi 30 novembre 2020 20:21
À : HUPO-PSI/psi-mod-CV <psi-mod-CV@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : Re: [HUPO-PSI/psi-mod-CV] PSI-MOD.obo.xml not up to date (#5)


I'm going to propose that we delete the .obo.xml or in some way mark it as deprecated. I don't have a way to generate the .obo.xml (which isn't OWL, but rather just a serialized obo file) and I don't plan on reverse-engineering it... thoughts?
