### ISSUE TITLE
Duplicate Names for sugars

### ISSUE THREAD

**Issue by pmt706** [HUPO-PSI/psi-mod-CV#54]
Need to address these duplications.

![image](https://user-images.githubusercontent.com/5824906/106956015-9fdfc980-66fb-11eb-9b96-afdd53f75b66.png)

**Comment by edeutsch** [comment]
should the children of apparently identical parents become mono-xxxxx residue?

**Comment by ricardblum** [comment]
Hi Paul,

I will have a look but not before 3 or 4 days.

Best wishes.

Sylvie.

Le 04/02/2021 à 22:15, Paul Thomas a écrit :

**Comment by pmt706** [comment]
@edeutsch, that's a great point.  all of the children are indeed mono-whatevers, so I just made that change.

**Comment by rfellers** [comment]
Not sure if these are a sugars, but there are a couple more duplicates.
* N-acetylaminoglucosylated residue (MOD:00448 and MOD:00733)
* N-acetylaminogalactosylated residue (MOD:00563 and MOD:00734)
