### ISSUE TITLE
NTR: glutaminylation ? 

### ISSUE THREAD

**Issue by edeutsch** [HUPO-PSI/psi-mod-CV#9]
New term request received via the old SourceForge site:
https://sourceforge.net/p/psidev/mod-controlled-vocab-changes/73/

Hello,

I would like to annotate the protein modification reported here:
PMID:28801462
"Protein glutaminylation is a yeast-specific posttranslational modification of elongation factor 1A."

but I can't locate anything relevent searching on "glutamin...."

Does it exist as another name, or does it need to be added

Not sure how to define, but it seems to be the attachment of a specific glutamine residue in a glutamate in ef1A

Thanks,

Val

**Comment by pmt706** [comment]
Hi Val, (crossposting this to both sites)

This isn't currently in the PSI-MOD CV, but certainly should be!  It would be similar to MOD:01970, but with a glutaminyl in place of the glutamyl.  I'll create the pull request over on github to add this modification.

Paul

**Comment by ValWood** [comment]
Thank's  both for migrating and sorting. I will also forward the new tracker info to the PomBase team.

**Comment by pmt706** [comment]
Fixed now in PSI-MOD.obo!

**Comment by ValWood** [comment]
thanks!

**Comment by ValWood** [comment]
Hi,

Can you provide the term name or ID for this term?
We updated our Modific nation ontology in our curation tool, but I can't locate anything searching on  "glutaminylation"

Thanks

Val

**Comment by pmt706** [comment]
Hi Val,

Sure, it’s MOD:02025.

Paul

**Comment by ValWood** [comment]
Thanks!

**Comment by ValWood** [comment]
I still don't locate this searching on 
glutaminyl... (no auto complete suggestions)
or MOD:02025

Could you confirm the  term name and ID?

Thanks

Val

CC @kimrutherford

**Comment by kimrutherford** [comment]
Hi Val.

That term is in the OBO file and will be in Canto on Thursday morning.

**Comment by ValWood** [comment]
Sorry, so impatient!

**Comment by pabinz** [comment]
Actually, there is no generic term for glutaminylated residue.
MOD:02025 is only valid for a 5-glutaminylated glutamic acid, which is the modification that is reported in PMID:28801462 (Protein glutaminylation is a yeast-specific posttranslational modification of elongation factor 1A, the case you have opened in february)
And it is the sole naturally occurring glutaminylation event reported in the literature, as far as I’m aware of.

Is that the mod you need?

Pierre-Alain



De : Val Wood <notifications@github.com>
Envoyé : mercredi 13 mai 2020 09:42
À : HUPO-PSI/psi-mod-CV <psi-mod-CV@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : Re: [HUPO-PSI/psi-mod-CV] NTR: glutaminylation ? (#9)


Sorry, so impatient!

**Comment by ValWood** [comment]
> Is that the mod you need?

Yes this is the modification that  I need. For the modification of elongation factor 1A.
But I  am very confused. Which is the term for this?


It isn't this one is it?

| MOD:02025
Ontology | PSI-MOD
Term name | 5-glutaminyl glutamic acid
Definition | A protein modification that effectively converts the alpha amino group of a glutamine residue to glutaminyl glutamic acid by forming an isopeptide bond with the side chain carboxyl group of a free glutamic acid.

**Comment by ValWood** [comment]
Or maybe that is correct?

**Comment by pabinz** [comment]
Yes, that is the correct term.

PSI-MOD terms describe modified residues. This means the chemical entity itself; in other words: the end product of a modification reaction on a "standard" residue. Here the term is :
5-glutaminyl glutamic acid
as the end product of a alpha-N-glutaminylation of the sidechain carboxyl group of a glutamic acid residue.

If you were looking for a modification term that represent an action, a chemical or enzymatic reaction, such as "glutaminylation", you will not find it in PSI-MOD. 


Similarly, you will find a term for a phosphoserine, for a phosphotyrosine, for a phosphorylated residue, that display mass difference of 80Da to apply to the target residue, but you will not find the term phosphorylation as PSI-MOD main term name. You will therefor find the end product of a phosphorylation, but not the phosphoorylation (re)action.

**Comment by ValWood** [comment]
Yes sorry,  I wanted the modification,  I should have typed I could not find anything when typing
"glutamin"  
We would use GO for "glutaminylation"

All sorted:
https://www.pombase.org/reference/PMID:28801462
